name: Compat Check w/PL - stable/latest

on:
  pull_request:
  schedule:
    - cron: "0 3 * * 1-5"  # Run daily at 3am Mon-Fri
  workflow_dispatch:

jobs:
  tests_linux:
    name: Lightning-Kokkos Compatibility test (tests_linux) - stable/latest
    uses: ./.github/workflows/tests_linux.yml
    with:
      lightning-kokkos-version: stable
      pennylane-version: latest

  tests_linux_x86_nvidia_gpu:
    name: Lightning-Kokkos Compatibility test (tests_linux_x86_nvidia_gpu) - stable/latest
    uses: ./.github/workflows/tests_linux_x86_nvidia_gpu.yml
    with:
      lightning-kokkos-version: stable
      pennylane-version: latest

