name: Compat Check w/PL - latest/stable

on:
  pull_request:
  schedule:
    - cron: "0 3 * * 1-5"  # Run daily at 3am Mon-Fri
  workflow_dispatch:

jobs:
  tests_linux:
    name: Lightning-Kokkos Compatibility test (tests_linux) - latest/stable
    uses: ./.github/workflows/tests_linux.yml
    with:
      lightning-kokkos-version: latest
      pennylane-version: stable

  tests_linux_x86_nvidia_gpu:
    name: Lightning-Kokkos Compatibility test (tests_linux_x86_nvidia_gpu) - latest/stable
    uses: ./.github/workflows/tests_linux_x86_nvidia_gpu.yml
    with:
      lightning-kokkos-version: latest
      pennylane-version: stable

