name: Set wheel build matrix

env:
  PYTHON3_MIN_VERSION: "8"
  PYTHON3_MAX_VERSION: "11"

on:
  workflow_call:
    inputs:
      event_name:
        required: true
        type: string
    outputs:
      python_version:
        description: "Python versions."
        value: ${{ jobs.set-builder-matrix.outputs.python_version }}
      cpu_exec_model:
        description: "Kokkos' cpu execution model."
        value: ${{ jobs.set-builder-matrix.outputs.cpu_exec_model }}
      macos_exec_model:
        description: "Kokkos' MacOS execution model."
        value: ${{ jobs.set-builder-matrix.outputs.macos_exec_model }}
      kokkos_version:
        description: "Kokkos version"
        value: ${{ jobs.set-builder-matrix.outputs.kokkos_version }}

jobs:
  set-builder-matrix:
    runs-on: ubuntu-22.04

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout PennyLane-Lightning-Kokkos
        uses: actions/checkout@v3

      - name: Python version
        id: pyver
        run: |
          if [[ ${{ inputs.event_name }} == 'pull_request' ]]; then
            echo "python_version=$(python3 scripts/gen_pyver_matrix.py \
              --min-version=3.${{ env.PYTHON3_MIN_VERSION }} \
              --max-version=3.${{ env.PYTHON3_MAX_VERSION }})" >> $GITHUB_OUTPUT
          else
            echo "python_version=$(python3 scripts/gen_pyver_matrix.py \
              --min-version=3.${{ env.PYTHON3_MIN_VERSION }} \
              --max-version=3.${{ env.PYTHON3_MAX_VERSION }} \
              --range)" >> $GITHUB_OUTPUT
          fi

      - name: Kokkos execution strategy (CPU)
        id: cpu_exec_model
        run: echo "cpu_exec_model=[\"SERIAL\",\"OPENMP\"]" >> $GITHUB_OUTPUT

      - name: Kokkos execution strategy (MacOS)
        id: macos_exec_model
        run: echo "macos_exec_model=[\"SERIAL\",\"THREADS\"]" >> $GITHUB_OUTPUT

      - name: Kokkos version
        id: kokkos_version
        run: echo "kokkos_version=[\"4.0.01\"]" >> $GITHUB_OUTPUT

    outputs:
      python_version: ${{ steps.pyver.outputs.python_version }}
      cpu_exec_model: ${{ steps.cpu_exec_model.outputs.cpu_exec_model }}
      macos_exec_model: ${{ steps.macos_exec_model.outputs.macos_exec_model }}
      kokkos_version: ${{ steps.kokkos_version.outputs.kokkos_version }}
