name: Tests::Linux::x86_64::Nvidia_GPU
on:
  release:
  push:
    branches:
      - main
  pull_request:

env:
  COVERAGE_FLAGS: "--cov=pennylane_lightning_kokkos --cov-report=term-missing --cov-report=xml:./coverage.xml --no-flaky-report -p no:warnings --tb=native" 
  GCC_VERSION: 11
  CI_CUDA_ARCH: 86

concurrency:
  group: gpu-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cpptests:
    runs-on:
      - self-hosted
      - ubuntu-22.04
      - gpu

    strategy:
      max-parallel: 1

    steps:
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.8'

      - name: Remove Ubuntu unattended upgrades
        run: sudo apt-get remove -y -q unattended-upgrades

      - name: Install required packages
        run: |
          sudo apt-get update && sudo apt-get -y -q install gcc-${{ env.GCC_VERSION }} g++-${{ env.GCC_VERSION }} gcovr lcov | apt --fix-broken install | \
          sudo apt-get update && sudo apt-get -y -q install gcc-${{ env.GCC_VERSION }} g++-${{ env.GCC_VERSION }} gcovr lcov
          python -m pip install ninja cmake~=3.24.3

      - name: Checkout PennyLane-Lightning-Kokkos
        uses: actions/checkout@v3

      - name: Validate GPU version and installed compiler
        run: |
          nvidia-smi
          /usr/local/cuda-11.8/bin/nvcc --version
      - name: Build and run unit tests
        run: |
            export PATH=/usr/local/cuda-11.8/bin:$PATH
            export LD_LIBRARY_PATH=/usr/local/cuda-11.8/lib64:$LD_LIBRARY_PATH
            cmake . -BBuild \
              -DKokkos_ENABLE_CUDA=ON \
              -DKokkos_ENABLE_SERIAL=ON \
              -DPLKOKKOS_BUILD_TESTS=ON \
              -G Ninja
            cmake --build ./Build
            ./Build/pennylane_lightning_kokkos/src/tests/runner_kokkos
      - name: Cleanup
        if: always()
        run: |
          rm -rf *
          rm -rf .git
          rm -rf .gitignore
          rm -rf .github
  pythontests:
    runs-on:
      - self-hosted
      - ubuntu-22.04
      - gpu

    strategy:
      max-parallel: 1

    steps:
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install required packages
        run: |
          sudo apt-get update && sudo apt-get -y -q install gcc-${{ env.GCC_VERSION }} g++-${{ env.GCC_VERSION }} gcovr lcov
          python -m pip install pip~=22.3
          python -m pip install ninja cmake~=3.24.3 pytest pytest-mock flaky pytest-cov wheel
          # Sync with latest master branches
          python -m pip install git+https://github.com/PennyLaneAI/pennylane.git@master
          python -m pip install --index-url https://test.pypi.org/simple/ pennylane-lightning --pre --force-reinstall --no-deps
          
      - name: Checkout pennyLane-lightning-kokkos
        uses: actions/checkout@v3

      - name: Build and install package
        run: |
          export PATH=/usr/local/cuda-11.8/bin:$PATH
          export LD_LIBRARY_PATH=/usr/local/cuda-11.8/lib64:$LD_LIBRARY_PATH
          CC=$(which gcc-${{ env.GCC_VERSION }}) CXX=$(which g++-${{ env.GCC_VERSION }}) BACKEND="CUDA" python -m pip install -e . --verbose

      - name: Run PennyLane-Lightning-Kokkos unit tests
        run: |
          pytest ./tests/
          pl-device-test --device lightning.kokkos --skip-ops --shots=20000
          pl-device-test --device lightning.kokkos --skip-ops --shots=None
      - name: Cleanup
        if: always()
        run: |
          rm -rf *
          rm -rf .git
          rm -rf .gitignore
          rm -rf .github
